### ISSUE TITLE
There is no document for usage...

### ISSUE THREAD

**Issue by wind13** [degree9/semui-hl#10]
From [hoplon](https://github.com/hoplon/hoplon) to get here. But there is no document for how to use it like some example code etc. It will be very helpful for others.

**Comment by burn2delete** [comment]
@wind13 see this file https://github.com/degree9/theLounge/blob/master/src/lounge/dash.cljs.hl

**Comment by wind13** [comment]
Cool! Thanks, and I think you should put this link in your home page `README.md` . 👍
