### ISSUE TITLE
Referencing Semui-hl on Hoplon page

### ISSUE THREAD

**Issue by tbrooke** [degree9/semui-hl#4]
I am having trouble referencing semui-hl   (The may be a newby thing)

I have  [degree9/semui-hl          "0.8.0"]  in both my build.boot and project.clj  

In my code: 
 (page "index.html"
   (:require
     [hoplon.twitter.bootstrap :refer [container]]   <= Disregard this it is going
     [sections.nav :as nav]
     [semantic-ui.modules.modal :as ui ]))

references modal but I apparently have to do one for each element 

It seem like the following should work but it doesn't
  [degree9.semui-hl :as ui] 

As suggested by others a simple example would help

**Comment by burn2delete** [comment]
At the moment you will need to import all the ui elements individually.

I believe you will also need to use alpha14 of hoplon for the semantic js to work. I havnt been able to get all the js working, so feedback is welcome!

You will need a `(link :rel "stylesheet" :type "text/css" :href "bower_components/semantic-ui/dist/semantic.css")` or however you feel like bringing in semantic css file, that one uses bower.

Examples will come after our production app launches, not much time right now, id like to rewrite the semantic-ui doc site using hoplon as the example app.

**Comment by burn2delete** [comment]
@tbrooke How has your semui-hl travels gone? Do you have a repo I can look at and point you in the right direction?
